# https://taskfile.dev

version: "3"

tasks:
  build:
    env:
      CGO_ENABLED: 0
    vars:
      VERSION: '{{ .VERSION | default "local" }}'
      GIT_COMMIT: '{{ .GIT_COMMIT | default "v0.0.0" }}'
      BUILD_OUTPUT: '{{ .BUILD_OUTPUT | default "./bin/server" }}'
      LDFLAGS: |
        -X main.version={{.VERSION}}
        -X main.Commit={{.GIT_COMMIT}}
    cmd: go build -o {{.BUILD_OUTPUT}} -ldflags "{{.LDFLAGS}}" ./cmd/server

  apply:
    dir: deployment/
    vars:
      LGTM: "alloy,tempo,grafana,loki"
    cmds:
      - kubectl apply -f namespace.yaml --wait=true
      - kubectl apply -f . --wait=true
      - |
        echo "📦 Updating Helm repositories..."
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
      - |
        echo "🔄 Deploying Prometheus..."
        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace observability \
          --values lgtm/prometheus/values.yaml \
          --wait --timeout=5m

      - cmd: |
          echo "{{.LGTM}}" | tr ',' '\n' | parallel -j 4 '
            echo "🔄 Deploying LGTM observability stack...Initializing {}..."
            helm upgrade --install {} grafana/{} \
              --namespace observability \
              --values lgtm/{}/values.yaml
          '
      - cmd: echo "Your grafana password is changeme123!"

  start:
    cmds:
      - minikube start
      - task: apply

  reset:
    cmds:
      - minikube delete
      - task: start
