alloy:
  # Run as DaemonSet to collect from all nodes
  mode: daemonset

  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    # OTLP HTTP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP

  # Stability level
  stabilityLevel: "generally-available"

  # Resource limits
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  # Configuration
  configMap:
    create: true
    content: |-

      // Traces collection
      otelcol.receiver.otlp "default" {
        grpc { }
        http { }

        output {
          traces  = [otelcol.processor.batch.default.input]
        }
      }

      otelcol.processor.batch "default" {
        output {
          traces = [otelcol.exporter.otlp.tempo.input]
        }
      }

      otelcol.exporter.otlp "tempo" {
        client {
          endpoint = "http://tempo-distributor.observability.svc.cluster.local:4317"
          tls {
            insecure = true
            insecure_skip_verify = true
          }
        }
      }

# Security context
securityContext:
  runAsUser: 473
  runAsGroup: 473
  fsGroup: 473
  runAsNonRoot: true
