apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    github: github.com/Alzgaymer/k8s-test
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - image: traefik/whoami
          name: traefik
          ports:
            - containerPort: 80
