apiVersion: v1
kind: Service
metadata:
  name: x-backend-svc
  namespace: x-backend
spec:
  selector:
    app: x
    tier: backend
  ports:
    - port: 80
      name: http
      targetPort: 8080
  type: NodePort
  externalIPs:
    - 192.168.0.10
