# Admin credentials
adminUser: admin
adminPassword: "changeme123!" # CHANGE THIS!

# Persistence
persistence:
  enabled: true
  size: 10Gi
  storageClass: "" # Use default storage class

# Resources
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Service configuration
service:
  type: LoadBalancer # or ClusterIP with Ingress
  port: 80

# Datasources configuration
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      # Prometheus
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.observability.svc.cluster.local
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 30s

      # Loki
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local
        editable: true
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "trace_id=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"

      # Tempo
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
        editable: true
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: prometheus
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true

# Dashboard providers
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

# Pre-install some dashboards
dashboards:
  default:
    # Kubernetes cluster monitoring
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus

    # Node exporter
    node-exporter:
      gnetId: 1860
      revision: 31
      datasource: Prometheus

    # Loki dashboard
    loki-logs:
      gnetId: 13639
      revision: 2
      datasource: Loki

# Plugins to install
plugins:
  - grafana-piechart-panel
  - grafana-clock-panel

# Environment variables
env:
  GF_SECURITY_ALLOW_EMBEDDING: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "false"
  GF_FEATURE_TOGGLES_ENABLE: "traceqlEditor"

# RBAC
rbac:
  create: true
  pspEnabled: false

# Service account
serviceAccount:
  create: true
