name: Build app and upload to Docker HUB

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
  workflow_dispatch:

jobs:
  build:
    name: Build & Push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: viacheslavzalitskyi/k8s-test:latest
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=latest
            GIT_COMMIT=${{ github.sha }}
          cache-from: type=registry,ref=viacheslavzalitskyi/k8s-test:latest
          cache-to: type=inline
